---
functional:
  - Пользователь должен иметь возможность создавать игры
  - Пользователь должен иметь возможность присоединяться к созданной игре 
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность общаться с другими пользователями в личных сообщениях
  - Пользователь должен иметь возможность общаться с другими пользователями в чате
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность создать игру без регистрации
  - Задачи реализованы на двух языках - русском и английском
  - Оба игрока видят два редактора, справа свой и соперника слева в режиме онлайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки неограниченно
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Возможность авторизации через Google
  - Русская версия сайта
  - У пользователя не должно быть возможности редактировать код соперника
  - Удобный интуитивно понятный интерфейс
